SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.usp_LiqList_PuedeAbrirR2SAP_v1
    @CodRol VARCHAR(20),
    @IdMenu VARCHAR(20) = '2.17'
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP (1) 1 AS PUEDE
    FROM P_MENUROL WITH (READUNCOMMITTED)
    WHERE COD_ROL = @CodRol
      AND IDMENU = @IdMenu;
END
GO

CREATE OR ALTER PROCEDURE dbo.usp_LiqList_FueProcesadaEnSAP_v1
    @CodigoLiquidacion INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT TOP (1) CODIGOOPERACION
    FROM MI3_SAP WITH (READUNCOMMITTED)
    WHERE CODIGOLIQUIDACION = @CodigoLiquidacion
      AND ESTATUS = 'T';
END
GO

