/*
  ROAD Toledano - Graph-path de una liquidacion
  Solo lectura. No contiene credenciales ni cambia estado.
  Ajustar parametros para reutilizar.
*/
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @Liquidacion int = 357515;
DECLARE @Cliente nvarchar(30) = '0001002150';
DECLARE @Producto nvarchar(30) = '0220';
DECLARE @Fecha date = '2026-07-20';
DECLARE @CantidadEvaluada float = 9.320;

-- Nodo 1: identidad, estado y responsables de la liquidacion.
SELECT L.*, V.NOMBRE AS VENDEDOR_NOMBRE, V.NIVEL AS NIVEL_VENDEDOR,
       V.NIVELPRECIO AS NIVELPRECIO_VENDEDOR, V.BODEGA, V.SUBBODEGA
FROM P_LIQUIDACION L
LEFT JOIN VENDEDORES V ON V.CODIGO = L.VENDEDOR AND V.RUTA = L.RUTA
WHERE L.CODIGO = @Liquidacion;

-- Nodo 2: cliente, segmentacion comercial y pertenencia/calendario de ruta.
SELECT C.CODIGO, C.NOMBRE, C.BLOQUEADO, C.TIPONEG, C.TIPO, C.SUBTIPO,
       C.CANAL, C.SUBCANAL, C.NIVELPRECIO, C.MEDIAPAGO, C.LIMITECREDITO,
       C.DIACREDITO, C.REGION, C.SUCURSAL, C.BODEGA, C.MODIF_PRECIO,
       C.PRIORIZACION, C.TIPOLOGIA, C.SUBTIPOLOGIA,
       CR.RUTA, CR.SEMANA, CR.DIA, CR.SECUENCIA
FROM P_CLIENTE C
LEFT JOIN P_CLIRUTA CR ON CR.CLIENTE = C.CODIGO
WHERE C.CODIGO = @Cliente
ORDER BY CR.RUTA, CR.DIA;

-- Nodo 3: maestro del producto, UM y factores de conversion.
SELECT * FROM P_PRODUCTO WHERE CODIGO = @Producto;
SELECT * FROM P_FACTORCONV WHERE PRODUCTO = @Producto ORDER BY UNIDADSUPERIOR;

-- Nodo 4: precio lista del nivel del cliente y precio especial exacto del dia/UM.
SELECT C.CODIGO AS CLIENTE, C.NIVELPRECIO, C.TIPO,
       PP.UNIDADMEDIDA, PP.PRECIO AS PRECIO_LISTA,
       (SELECT TOP (1) PE.PRECIO
          FROM P_PRECESPEC PE
         WHERE ((PE.CODIGO = 'RUTA' AND PE.VALOR = @Cliente)
             OR (PE.CODIGO = 'TIPO' AND PE.VALOR = C.TIPO)
             OR (PE.CODIGO = 'CLIENTE' AND PE.VALOR = @Cliente))
           AND PE.PRODUCTO = @Producto
           AND CAST(PE.FECHA AS date) = @Fecha
           AND PE.UNIDADMEDIDA = PP.UNIDADMEDIDA
         ORDER BY PE.CODIGO, PE.FECHA DESC) AS PRECIO_ESPECIAL
FROM P_CLIENTE C
JOIN P_PRODPRECIO PP ON PP.CODIGO = @Producto AND PP.NIVEL = C.NIVELPRECIO
WHERE C.CODIGO = @Cliente;

-- Nodo 5: inventario operativo que frmFM considera disponible.
SELECT T.CODIGOPRODUCTO, T.UM, COUNT(*) AS FILAS,
       COUNT(DISTINCT T.BARRA) AS BARRAS,
       SUM(ABS(T.CANTIDADINICIAL)) AS CANTIDAD_INICIAL,
       SUM(T.CANTIDADUTILIZADA) AS CANTIDAD_USADA,
       SUM(T.CANTIDADDL) AS CANTIDAD_DL,
       SUM(T.CANTIDADPALLET) AS CANTIDAD_PALLET,
       SUM(ABS(T.CANTIDADINICIAL))-SUM(T.CANTIDADUTILIZADA)-SUM(T.CANTIDADDL) AS CANTIDAD_DISPONIBLE,
       SUM(T.PESOINICIAL) AS PESO_INICIAL,
       SUM(T.PESOUTILIZADO) AS PESO_USADO,
       SUM(T.PESODL) AS PESO_DL,
       SUM(T.PESOPALLET) AS PESO_PALLET,
       SUM(T.PESOINICIAL)-SUM(T.PESOUTILIZADO)-SUM(T.PESODL) AS PESO_DISPONIBLE
FROM TEMP_STOCK_LIQUIDACION T
WHERE T.CODIGOLIQUIDACION = @Liquidacion
  AND (@Producto = '' OR T.CODIGOPRODUCTO = @Producto)
GROUP BY T.CODIGOPRODUCTO, T.UM
ORDER BY T.CODIGOPRODUCTO;

SELECT *
FROM TEMP_STOCK_LIQUIDACION
WHERE CODIGOLIQUIDACION = @Liquidacion
  AND (@Producto = '' OR CODIGOPRODUCTO = @Producto)
ORDER BY CODIGOPRODUCTO, CODSTOCK;

-- Nodo 6: condicion que replica la seleccion no-combo actual de frmFM/DAL.
SELECT TOP (1) D.*
FROM P_DESCUENTO D
CROSS JOIN P_CLIENTE C
WHERE C.CODIGO = @Cliente
  AND (D.CTIPO = 0
       OR (D.CTIPO = 1 AND D.CLIENTE = C.CODIGO)
       OR (D.CTIPO = 3 AND D.CLIENTE = C.TIPO))
  AND @CantidadEvaluada BETWEEN D.RANGOINI AND D.RANGOFIN
  AND D.ES_RECARGO = 0
  AND D.PTIPO < 4
  AND D.PRODUCTO = @Producto
  AND D.DESCTIPO = 'R'
  AND D.GLOBDESC = 'N'
  AND @Fecha BETWEEN CAST(D.FECHAINI AS date) AND CAST(D.FECHAFIN AS date)
  AND NOT EXISTS (
      SELECT 1
      FROM P_CLIENTE_PROD_EXCLUIDOS E
      WHERE E.CLIENTE = @Cliente AND E.PRODUCTO = @Producto AND E.ACTIVO = 1
        AND @Fecha BETWEEN E.FECHAINI AND E.FECHAFIN)
ORDER BY D.PRIORIDAD_DESCUENTO, D.PRIORIDAD;

-- Nodo 7: ventas persistidas; una FM aun abierta solo vive en memoria del formulario.
SELECT F.*
FROM D_FACTURA F
WHERE F.CODIGOLIQUIDACION = @Liquidacion
ORDER BY F.FECHA, F.COREL;

SELECT F.COREL, F.SERIE, F.CLIENTE, F.ANULADO,
       D.*, P.DESCCORTA
FROM D_FACTURA F
JOIN D_FACTURAD D ON D.COREL = F.COREL
LEFT JOIN P_PRODUCTO P ON P.CODIGO = D.PRODUCTO
WHERE F.CODIGOLIQUIDACION = @Liquidacion
ORDER BY F.COREL, D.VAL2;

-- Nodo 8: notas credito/debito vinculadas a la liquidacion y factura.
SELECT N.*, ND.POSICION, ND.PRODUCTO, ND.CANTIDAD, ND.PESO, ND.PRECIO,
       ND.DIFERENCIA, ND.TOTAL AS TOTAL_DETALLE, ND.LOTE,
       ND.UMVENTA, ND.UMSTOCK, ND.UMPESO
FROM P_NOTACD N
LEFT JOIN P_NOTACDD ND ON ND.CODIGONCD = N.CODIGONCD
WHERE N.CODIGOLIQUIDACION = @Liquidacion
ORDER BY N.CODIGONCD, ND.POSICION;
