select * from P_STOCK where ruta = '1002-3' and fecha between '20230117' and '20230228'

insert into P_STOCK
select [RUTA], [CODIGO], [CANT], [CANTM], [PESO], [plibra], [LOTE],'0983179242' [DOCUMENTO],
'20230118' [FECHA], [ANULADO], [CENTRO], [STATUS],0 [ENVIADO], 
0[CODIGOLIQUIDACION],'' [COREL_D_MOV], GETDATE() [FECHA_SISTEMA], [UNIDADMEDIDA], [DOC_ENTREGA]
from P_STOCK
where documento = '0083179242'

select * from P_COREL where ruta = '1002-3'
update P_COREL set CORELULT = 220  where ruta = '1002-3'

select * from P_EMPRESA

ALTER TABLE P_EMPRESA
ADD URL_BASE nvarchar(150) NULL,
URL_TOKEN	nvarchar(150)	NULL,
QR_API	nvarchar(200)	NULL,
ARCHIVO_P12	nvarchar(150)	NULL,
QR_CLAVE	nvarchar(50)	NULL,
URL_B2C_HH	nvarchar(150)	NULL

ALTER TABLE P_CLIENTE
ADD DESCRIPCION_PAGO NVARCHAR(100) NULL

ALTER TABLE P_EMPRESA ADD URL_AUTENTICACION NVARCHAR(150)
ALTER TABLE P_EMPRESA ADD USUARIO_API NVARCHAR(50)
ALTER TABLE P_EMPRESA ADD CLAVE_API NVARCHAR(50)
ALTER TABLE P_EMPRESA ADD URL_ANULACION NVARCHAR(150)

UPDATE P_EMPRESA SET URL_AUTENTICACION = 'https://labpa.guru-soft.com/EdocPanama/4.0/Autenticacion/Api/ServicioEDOC?Id=1'
UPDATE P_EMPRESA SET USUARIO_API = 'edocTOLEDANO_8945'
UPDATE P_EMPRESA SET CLAVE_API = 'wsTOLEDANO_8945'
UPDATE P_EMPRESA SET URL_ANULACION = 'https://labpa.guru-soft.com/eDocPanama/4.0/Emision/Eventos/API/Anulacion'

ALTER TABLE P_EMPRESA ADD URL_CONSULTA_DOCUMENTOS_POR_CRITERIO NVARCHAR(250)
UPDATE P_EMPRESA SET URL_CONSULTA_DOCUMENTOS_POR_CRITERIO = 'https://labpa.guru-soft.com/eDocPanama/4.0/Emision/Consulta/Api/EstadoDocumentoPorCriterios'

URL_EMISION_FACTURA_B2C TEXT,
URL_EMISION_NC_B2C TEXT,
URL_EMISION_ND_B2C TEXT,
URL_BASE TEXT,
URL_TOKEN TEXT,
QR_API TEXT,
ARCHIVO_P12 TEXT,
QR_CLAVE TEXT,
URL_B2C_HH TEXT,