SELECT F.FECHA,CONCAT(F.SERIE, RIGHT(CONCAT('000000',F.CORELATIVO),6)) FACTURA, F.ORDEN_COMPRA,       
	   F.TOTAL, F.CLIENTE, C.NOMBRE NOM_CLIENTE, F.RUTA, R.NOMBRE NOM_RUTA, F.VENDEDOR, V.NOMBRE NOM_VENDEDOR
FROM D_FACTURA F INNER JOIN 
     P_CLIENTE C ON F.CLIENTE = C.CODIGO INNER JOIN
	 P_VENDEDOR V ON F.VENDEDOR = V.CODIGO INNER JOIN 
	 P_RUTA R ON R.CODIGO = F.RUTA
WHERE FECHA BETWEEN '20250101 00:00:00' AND '20250228 23:59:59'

