 SELECT T.RUTA, T.CODIGO, P.DESCLARGA AS NOMBRE,  -SUM(T.CANT) AS CANT,  -SUM(T.PESO) AS PESO, SUM(T.CANTDEV) AS CANTDEV,  
	 SUM(T.PESODEV) AS PESODEV, -SUM(T.CANT)+SUM(T.CANTDEV)+SUM(T.CANTDL) AS DIFCANT,
	 -SUM(T.PESO)+ SUM(T.PESODEV)+SUM(T.PESODL) AS DIFPESO, T.UNIDADMEDIDA, T.UMDOCDEV  
 FROM (
 
 SELECT D_CXC.RUTA, D_CXCD.CODIGO, SUM(CANT) AS CANT,  SUM(PESO) AS PESO , 0 AS CANTDEV, 0 AS PESODEV, 0 AS CANTDL,
       0 AS PESODL,  CASE WHEN D_CXCD.UMVENTA = 'KG' THEN D_CXCD.UMSTOCK ELSE D_CXCD.UMVENTA END AS UNIDADMEDIDA, 
	   '' AS UMDOCDEV 
 FROM D_CXC INNER JOIN D_CXCD ON D_CXC.COREL = D_CXCD.COREL  
 WHERE DATEDIFF (DAY, D_CXC.FECHA, '20230822')=0 AND D_CXC.RUTA = '8210-1' AND   D_CXCD.ESTADO IN( 'M','B')  
		 AND D_CXC.ANULADO = 'N' AND D_CXC.COREL NOT LIKE 'CM%' AND CODIGOLIQUIDACION = 291263 
		 AND D_CXC.COREL IN (SELECT FACTURA 
		                    FROM D_NOTACRED 
							WHERE TIPO_DOCUMENTO = 'NC' AND RUTA = '8210-1' 
								AND VENDEDOR = '00101390' AND ANULADO = 'N'  AND FECHA = '20230822' 
								AND CODIGOLIQUIDACION = 291263  
							UNION
							SELECT ASIGNACION 
							FROM D_FACTURA 
							WHERE RUTA = '8210-1' 
									AND VENDEDOR = '00101390' AND ANULADO = 'N'  AND FECHA = '20230822' 
									AND CODIGOLIQUIDACION = 291263 )  
GROUP BY D_CXC.RUTA,D_CXCD.CODIGO, 
        CASE WHEN D_CXCD.UMVENTA = 'KG' THEN D_CXCD.UMSTOCK ELSE D_CXCD.UMVENTA END  
UNION  
SELECT D_CXC.RUTA, D_CXCD.CODIGO, SUM(CANT) AS CANT,  SUM(PESO) AS PESO , 0 AS CANTDEV, 0 AS PESODEV, 0 AS CANTDL, 
       0 AS PESODL,  CASE WHEN D_CXCD.UMVENTA = 'KG' THEN D_CXCD.UMSTOCK ELSE D_CXCD.UMVENTA END AS UNIDADMEDIDA, 
	   '' AS UMDOCDEV  
FROM D_CXC INNER JOIN 
	  D_CXCD ON D_CXC.COREL = D_CXCD.COREL  
WHERE DATEDIFF (DAY, D_CXC.FECHA, '20230822')=0 AND D_CXC.RUTA = '8210-1' AND   D_CXCD.ESTADO IN( 'M','B')  AND 
     D_CXC.ANULADO = 'N' AND D_CXC.COREL LIKE 'CM%' AND CODIGOLIQUIDACION = 291263 AND 
	 D_CXC.COREL IN (SELECT FACTURA FROM D_NOTACRED WHERE TIPO_DOCUMENTO = 'NC' AND RUTA = '8210-1' 
                    AND VENDEDOR = '00101390' AND ANULADO = 'N'  AND FECHA = '20230822' 
                    AND CODIGOLIQUIDACION = 291263  UNION
					SELECT ASIGNACION FROM D_FACTURA WHERE RUTA = '8210-1' 
                    AND VENDEDOR = '00101390' AND ANULADO = 'N'  AND FECHA = '20230822' 
                    AND CODIGOLIQUIDACION = 291263 )  
GROUP BY D_CXC.RUTA,D_CXCD.CODIGO, CASE WHEN D_CXCD.UMVENTA = 'KG' THEN 
                    D_CXCD.UMSTOCK ELSE D_CXCD.UMVENTA END  
UNION  
SELECT P_STOCK.RUTA, CODIGO, 0 AS CANT, 0 AS PESO, SUM(CANT) AS CANTDEV,  SUM(PESO) AS PESODEV, 0 AS CANTDL, 0 AS PESODL, 
       P_STOCK.UNIDADMEDIDA AS UNIDADMEDIDA, '' AS UMDOCDEV  
FROM P_STOCK  
WHERE P_STOCK.FECHA = '20230822' AND P_STOCK.RUTA = '8210-1'   
     AND P_STOCK.STATUS IN ('D','E') AND CODIGOLIQUIDACION = 291263 AND P_STOCK.ANULADO = 0 
GROUP BY  P_STOCK.CODIGO, P_STOCK.RUTA, P_STOCK.UNIDADMEDIDA  
UNION   
SELECT P_STOCKB.RUTA, CODIGO, 0 AS CANT, 0 AS PESO, SUM(CANT) AS CANTDEV,  SUM(PESO) AS PESODEV, 0 AS CANTDL, 
       0 AS PESODL, P_STOCKB.UNIDADMEDIDA AS UNIDADMEDIDA, '' AS UMDOCDEV  
FROM P_STOCKB   
WHERE P_STOCKB.FECHA = '20230822' AND P_STOCKB.RUTA = '8210-1'   AND P_STOCKB.STATUS IN ('D','E')  
      AND CODIGOLIQUIDACION   = 291263 AND P_STOCKB.ANULADO = 0 
GROUP BY P_STOCKB.RUTA, P_STOCKB.CODIGO, P_STOCKB.UNIDADMEDIDA  
UNION  
SELECT '8210-1' AS RUTA, D.PRODUCTO, 0 AS CANT, 0 AS PESO, 0 AS CANTDEV,    0 AS PESODEV, SUM(D.CANTIDAD) AS CANTDL, 
SUM(D.PESO) AS PESODL, CASE WHEN D.UMVENTA = 'KG' THEN D.UMSTOCK ELSE D.UMVENTA END AS UNIDADMEDIDA, '' AS UMDOCDEV  
FROM P_DIFLIQ E INNER JOIN  P_DIFLIQ_DET D ON  E.CODIGO = D.CODIGO AND E.CODIGO_LIQUIDACION = D.CODIGOLIQUIDACION  
WHERE E.FECHA = '20230822' AND E.RAZON = 'FALTANTE PRODUCTO DAÑADO' AND E.CODIGO_ESTADO <> 'ANULADO'  
     AND E.CODIGO_LIQUIDACION = 291263 AND E.VENDEDOR = '00101390'  
GROUP BY  D.PRODUCTO, CASE WHEN D.UMVENTA = 'KG' THEN D.UMSTOCK ELSE D.UMVENTA END

) AS T INNER JOIN P_PRODUCTO P 
                    ON T.CODIGO = P.CODIGO 
                    WHERE P.ES_CANASTA =0 
                    GROUP BY T.RUTA, T.CODIGO, P.DESCLARGA, T.UNIDADMEDIDA, T.UMDOCDEV