SELECT *
FROM CONF_INTERFASE
WHERE EXP_IMP = 1

--UPDATE CONF_INTERFASE SET PROCESADA = 0
--WHERE EXP_IMP = 1 AND TABLA = 'P_DIFLIQ'

--DELETE from ROADSAP_HIST_4.dbo.P_DIFLIQ_DET
--where  CODIGOLIQUIDACION IN 
--(SELECT CODIGO_LIQUIDACION FROM ROADSAP_HIST_4.dbo.P_DIFLIQ WHERE FECHA  between  '20220801' and '20220819')

--DELETE  from ROADSAP_HIST_4.dbo.P_DIFLIQ
--WHERE FECHA  between '20220801' and '20220819'
	
declare @registros int
exec sP_COMPARATIVO_HISTORICO '20220513','20220831',@registros
select * from P_COMPARATIVO_HISTORICO WHERE tabla like 'P_DIFLIQ%' order by año, mes, dia


