select E.COREL, E.FECHA, E.CLIENTE, E.RUTA, ISNULL(FE.VENDEDOR,'') VENDEDOR, V.PRODUCTO,
       D.CANT_ORIGINAL CANTIDAD_OFERTA, D.PESO_ORIGINAL PESO_OFERTA,D.UMVENTA UMVENTAOFERTA, D.UMSTOCK UMSTOCKOFERTA,
	   D.UMPESO UMPESOOFERTA,D.CANT CANTIDAD_PRIORIZADO, D.PESO PESO_PRIORIZADO,
	   FE.COREL AS FACTURA, ISNULL(FD.CANT,0) CANT_ENTREGADA, ISNULL(D.TOTAL,0) MONTO, ISNULL(FD.PESO,0) PESO_ENTREGADO,
	   D.UMVENTA, D.UMSTOCK,D.UMPESO, V.IDRAZON RAZON_NO_ENTREGA, R.DESCRIPCION
from D_DESPACHOD_NO_ENTREGADO v inner join 
     P_RAZON_DESP_INCOMP r ON v.IDRAZON = r.IDRAZON left join
     DS_PEDIDO e on v.COREL = e.COREL left JOIN
     DS_PEDIDOD d ON e.corel = d.corel and d.PRODUCTO = v.PRODUCTO left join
	 d_factura fe on fe.DESPCOREL = V.COREL left join
	 D_FACTURAD fd on fe.COREL = fd.COREL and v.producto = fd.producto
where e.FECHA between '20250101' and '20250905' and fe.anulado = 'N'

select top(10) * from D_DESPACHOD_NO_ENTREGADO
select top(10) * from DS_PEDIDO
select top(10) * from DS_PEDIDOD
