ALTER VIEW [dbo].[VW_CLIENTES_NUEVOS] AS
SELECT C.FECHA, C.RUTA, C.CODIGO,  C.NOMBRE, C.DIRECCION, 
C.NIT AS RUC, 
CASE WHEN C.IMAGEN IS NULL THEN 'NO' ELSE 'SI' END AS TIENE_IMAGEN,
S.EMPRESA, E.NOMBRE AS NOM_EMPRESA,
S.CODIGO AS CODIGO_SUCURSAL, S.NOMBRE AS NOM_SUCURSAL, C.CODIGO_ERP, C.STATCOM, 'D_CLINUEVO' AS TIPO,
'N/D' CANAL, 'N/D' SUBCANAL, 'ND' TIPOLOGIA, 0 RUC_VALIDADO
FROM D_CLINUEVO C INNER JOIN P_RUTA R ON C.RUTA = R.CODIGO
INNER JOIN P_SUCURSAL S ON R.SUCURSAL = S.CODIGO
INNER JOIN P_EMPRESA E ON S.EMPRESA = E.EMPRESA
UNION
SELECT C.FECHA, C.RUTA, C.CODIGO,  C.NOMBRE, C.DIRECCION, 
C.NIT AS RUC, 
CASE WHEN C.IMAGEN IS NULL THEN 'NO' ELSE 'SI' END AS TIENE_IMAGEN,
S.EMPRESA, E.NOMBRE AS NOM_EMPRESA,
S.CODIGO AS CODIGO_SUCURSAL, S.NOMBRE AS NOM_SUCURSAL, C.CODIGO_ERP, C.STATCOM, 'D_CLINUEVOT' AS TIPO,
ISNULL(N.CODIGO + ' ' + N.NOMBRE,'N/D') CANAL, 
ISNULL(B.CODIGO + ' ' + B.NOMBRE,'N/D') SUBCANAL,
ISNULL(T.CODIGO + ' ' + T.NOMBRE,'N/D') TIPOLOGIA,
C.RUC_VALIDADO
FROM D_CLINUEVOT C INNER JOIN P_RUTA R ON C.RUTA = R.CODIGO
INNER JOIN P_SUCURSAL S ON R.SUCURSAL = S.CODIGO
INNER JOIN P_EMPRESA E ON S.EMPRESA = E.EMPRESA
LEFT JOIN P_CANAL N ON N.CODIGO = C.CANAL
LEFT JOIN P_CANALSUB B ON B.CODIGO = C.SUBCANAL
LEFT JOIN P_TIPOLOGIA T ON T.CODIGO = C.TIPOLOGIA
GO

--#CKFK20240606
ALTER TABLE D_PEDIDO ADD TIPO_PEDIDO nvarchar(10) null,
TOTAL_MONTO_MINIMO  INT NOT NULL DEFAULT 0
GO

--#CKFK20240606
ALTER TABLE D_CLINUEVOT ADD RUC_VALIDADO BIT not null Default 0
GO

ALTER TABLE P_EMPRESA ADD URL_LOTE_RUC_DV NVARCHAR(150)
GO

UPDATE P_EMPRESA SET URL_LOTE_RUC_DV = 'https://pa.edocnube.com/4.0/Emision/Consulta/Api/LoteRucDV'

INSERT INTO P_MENUSISTEMA VALUES('1.4.9',1,'Monto mínimo pedidos','tsmiMontoMinimoPedidos',	2,'1.4')
INSERT INTO P_MENUROL VALUES(1, 3900, '1.4.9',1,1)
INSERT INTO P_MENUROL VALUES(13, 3903, '1.4.9',1,1)
INSERT INTO P_MENUROL VALUES(14, 3903, '1.4.9',1,1)
INSERT INTO P_MENUROL VALUES(41, 3905, '1.4.9',1,1)
INSERT INTO P_MENUROL VALUES(42, 3905, '1.4.9',1,1)
INSERT INTO P_MENUROL VALUES(27, 3904, '1.4.9',1,1)

--2024-07-15 Parametrizar permiso Razones de despacho incompleto
INSERT INTO P_MENUSISTEMA VALUES('1.9.11',1,'Razones de despacho incompleto','tsmiRazonesDeDespachoIncompleto',	3,'1.9')
INSERT INTO P_MENUROL VALUES(1, 3900, '1.9.11',1,1)
INSERT INTO P_MENUROL VALUES(13, 3903, '1.9.11',1,1)
INSERT INTO P_MENUROL VALUES(14, 3903, '1.9.11',1,1)
INSERT INTO P_MENUROL VALUES(41, 3905, '1.9.11',1,1)
INSERT INTO P_MENUROL VALUES(42, 3905, '1.9.11',1,1)
INSERT INTO P_MENUROL VALUES(27, 3904, '1.9.11',1,1)

--2024-05-04 Nuevo filtro para clientes
INSERT INTO P_MENUSISTEMA VALUES('1.4.8',1,'Tipología','tsmiTipologia',	2,'1.4')
INSERT INTO P_MENUROL VALUES(1, 3900, '1.4.8',1,1)
INSERT INTO P_MENUROL VALUES(1, 3905, '1.4.8',1,1)
INSERT INTO P_MENUROL VALUES(1, 3903, '1.4.8',1,1)

ALTER TABLE P_RAZON_DESP_INCOMP ADD ACTIVO BIT NOT NULL DEFAULT 1
GO

ALTER TABLE P_SUCURSAL ADD MM_INCLUYE_CERRADOS BIT NOT NULL DEFAULT 1
GO

INSERT INTO P_PARAMEXT VALUES(38,'','Distancia KM cliente hacia el CD', 50)
GO

ALTER TABLE P_MONTO_MINIMO_CLIENTE
	ADD SETUP int NOT NULL  DEFAULT ((0))
GO	